<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('import_batches',function(Blueprint $t){$t->id();$t->foreignId('store_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('type',30);$t->string('original_filename');$t->string('file_hash',64);$t->date('source_start_date')->nullable();$t->date('source_end_date')->nullable();$t->string('status',30)->default('processing');$t->unsignedInteger('rows_read')->default(0);$t->unsignedInteger('created_count')->default(0);$t->unsignedInteger('updated_count')->default(0);$t->unsignedInteger('error_count')->default(0);$t->json('summary')->nullable();$t->string('backup_path')->nullable();$t->text('error_message')->nullable();$t->timestamp('rolled_back_at')->nullable();$t->timestamps();$t->index(['store_id','type','created_at']);$t->index('file_hash');});
  Schema::create('import_errors',function(Blueprint $t){$t->id();$t->foreignId('import_batch_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('row_number')->nullable();$t->string('code',80)->nullable();$t->text('message');$t->json('raw')->nullable();$t->timestamps();});
  Schema::create('data_coverage_days',function(Blueprint $t){$t->id();$t->foreignId('store_id')->constrained()->cascadeOnDelete();$t->string('type',30);$t->date('date');$t->foreignId('import_batch_id')->nullable()->constrained()->nullOnDelete();$t->timestamps();$t->unique(['store_id','type','date']);});
  Schema::create('activity_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('store_id')->nullable()->constrained()->nullOnDelete();$t->string('action',120);$t->string('entity_type',120)->nullable();$t->string('entity_id',120)->nullable();$t->json('meta')->nullable();$t->timestamps();$t->index(['store_id','created_at']);});
  Schema::create('monthly_closings',function(Blueprint $t){$t->id();$t->foreignId('store_id')->constrained()->cascadeOnDelete();$t->date('month');$t->json('snapshot');$t->boolean('is_stale')->default(false);$t->foreignId('closed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('closed_at');$t->timestamps();$t->unique(['store_id','month']);});
 }
 public function down(): void {Schema::dropIfExists('monthly_closings');Schema::dropIfExists('activity_logs');Schema::dropIfExists('data_coverage_days');Schema::dropIfExists('import_errors');Schema::dropIfExists('import_batches');}
};
