<?php
namespace App\Http\Controllers;
use App\Models\ActivityLog; use App\Models\ProductVariant; use App\Models\Store; use App\Models\StoreFeeHistory; use App\Models\VariantCostHistory; use App\Services\Reports\ClosingStaleService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class CostController extends Controller
{
 public function variantCosts(Request $r,Store $store,ClosingStaleService $closings){$d=$r->validate(['effective_from'=>'required|date','rows'=>'required|array|min:1','rows.*.variant_id'=>'required|integer','rows.*.hpp'=>'required|integer|min:0','rows.*.admin_percent'=>'nullable|numeric|min:0|max:100']);$ids=collect($d['rows'])->pluck('variant_id');$valid=ProductVariant::where('store_id',$store->id)->whereIn('id',$ids)->pluck('id')->all();if(count($valid)!==count(array_unique($ids->all())))return response()->json(['message'=>'Ada variasi yang bukan milik toko ini.'],422);DB::transaction(function()use($d,$r){foreach($d['rows'] as $row)VariantCostHistory::updateOrCreate(['product_variant_id'=>$row['variant_id'],'effective_from'=>$d['effective_from']],['hpp'=>$row['hpp'],'admin_percent'=>$row['admin_percent']??null,'created_by'=>$r->user()->id]);});$closings->range($store->id,$d['effective_from']);ActivityLog::create(['user_id'=>$r->user()->id,'store_id'=>$store->id,'action'=>'cost.bulk_updated','meta'=>['effective_from'=>$d['effective_from'],'count'=>count($d['rows'])]]);return response()->json(['ok'=>true]);}
 public function storeFee(Request $r,Store $store,ClosingStaleService $closings){$d=$r->validate(['effective_from'=>'required|date','default_admin_percent'=>'required|numeric|min:0|max:100','fixed_fee_per_order'=>'required|integer|min:0']);$fee=StoreFeeHistory::updateOrCreate(['store_id'=>$store->id,'effective_from'=>$d['effective_from']],$d+['created_by'=>$r->user()->id]);$closings->range($store->id,$d['effective_from']);ActivityLog::create(['user_id'=>$r->user()->id,'store_id'=>$store->id,'action'=>'store_fee.updated','meta'=>$d]);return response()->json(['fee'=>$fee]);}
 public function feeHistory(Store $store){return response()->json(['fees'=>$store->feeHistories()->orderByDesc('effective_from')->get()]);}
}
